### ISSUE TITLE
[ECE-Tools] Conditionally Execute setup:upgrade During Deployment

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/ece-tools#419]
During deploy phase `bin/magento setup:upgrade --keep-generated` is executed every time. This increase time necessary for actual deployment.
Magento 2.2 introduce the command `bin/magento setup:db:status` to check whether an upgrade is required or not.

Couldn't add this check in `vendor/magento/ece-tools/src/Process/Deploy/InstallUpdate/Update/Setup.php` to reduce unnecessary maintenance time?

Furthermore: Wouldn't this allow to avoid maintenance mode if no DB updates are required?

**Comment by YPyltiai** [comment]
Hi @phoenix-bjoern , thanks for posting this request! We'll review it and will get back to you with comments. Last time we looked at using this approach, I remember something stopped us from proceeding.

@kandy , would love to hear your thoughts on it. I believe we discussed it before but there were some concerns on following this path.

**Comment by YPyltiai** [comment]
Internal ticket to review this approach created under ID: `MAGECLOUD-3183`

**Comment by arhiopterecs** [comment]
This is not necessary since the command checks the compliance of the versions of the modules and starts the upgrade process only in case the version of the module in the configuration is higher than the version of the installed module.
In case if the versions of the modules did not change, then the command is executed approximately ~ 3 seconds. (2.972687959671 - 3.31223487854 sec)

**Comment by YPyltiai** [comment]
Hi @phoenix-bjoern ,

Please see the result of investigation above. Did you experience some different results?
If so, may you please share version of core you used?

Thanks,
Yevhenii

**Comment by phoenix-bjoern** [comment]
@YPyltiai for those 3 seconds the maintenance mode is enabled although not necessary. At the end we are seeking for zero downtime during deployment which isn't possible if a lot of stuff is done which is relevant while the shop is down.

**Comment by YPyltiai** [comment]
@phoenix-bjoern , based on our review `bin/magento setup:db:status` will take nearly the same amount of time as an empty `bin/magento setup:upgrade`, when there are no DB changes required. We also queue connections for those 3 seconds of delay, so you won't hit 503 anyway in both cases. At this point we are not sure that we want to make logic more complicated there with no immediate benefits as an outcome.

Hope additional details help.

**Comment by BarnyShergold** [comment]
I've just discovered this proposal after creating a patch to do just this.

For metrics I got the patch to do the setup:db:status and the setup:upgrade and log when they started and ended.

I've now run this patch 4 times on a PRO-12 Staging environment - where no database was updated and the numbers are consistent.

The check takes on average 5.5s
The empty upgrade takes on average 13.75s

So on an average run checking to see if the database doesn't need updating SAVES 8.25s

Whilst it would in theory increase a DB update deploy by 5.5s, these should be a LOT less prevalent than non-update deploys AND good DEVOPS says you should (in theory) do schema and functional deploys separately (so DB updates can be done in quieter times)

I do feel that this proposal should be re-opened and reviewed. 

I have the code changes ready and waiting :)

**Comment by YPyltiai** [comment]
Hi @BarnyShergold ,

Thanks for sharing your thought on this one.

If you have code ready, would you mind submitting PR for us to test this use case once again? Things may have changed since last time we looked at it.

Thanks,
Yevhenii

**Comment by BarnyShergold** [comment]
Hi
I certainly can - can you tell me or point me at the process for creating a PR? I've cloned the repo

**Comment by YPyltiai** [comment]
@BarnyShergold , we don't have some special rules for ECE-Tools. Process is as simple as:
1. Fork repo
2. Add changes in your fork and submit PR upstream
3. We will see the PR and help testing/validating it. Tests will need to be green but that is something our team can help with,

**Comment by YPyltiai** [comment]
Closing per comments in #619
