### ISSUE TITLE
pub/static/.htaccess file is deleted by StaticContentCleaner

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/ece-tools#454]
During deployment pub/static/.htaccess is deleted when SCD_ON_DEMAND=true is set. This is because the whole directory "static" is cleaned without any excludes.

Without the .htaccess file Apache doesn't generate the static content on the fly as intended by the SCD_ON_DEMAND setting.

Adding ".htaccess" to the exclude array would resolve this issue.

**Comment by shiftedreality** [comment]
Hello @phoenix-bjoern,

Could you describe the usage of Apache on your project?
We don't use it on Cloud and there may be some other places which we didn't cover because of this.

**Comment by phoenix-bjoern** [comment]
@shiftedreality not sure if I get you question correct. We have an Apache + mod_php setup. Since the Magento specific settings are defined the the .htaccess files located in pub/.htaccess and pub/static/.htaccess the behavior defined in this files won't be triggered if they are aren't present. The results are 404 errors and others. So, not having the .htaccess files will not allow to run the application correctly.

**Comment by YPyltiai** [comment]
This issue will be addressed in scope of #455 and `MAGECLOUD-3545`.
Closing issue in favor of #455
