### ISSUE TITLE
[ECE-Tools] Removed index.php from the URL Breaks Multi-website Setup

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#461]
Internal ID: `MAGECLOUD-3496`

### Background:
- We've found a regression bug caused by #430

#### Pre-conditions:
- Url Rewrite is enabled 
- websites were configured in *magento-vars.php*
- websites have the same domain. Websites differ by path of URI (https://mydomain.com/website1/, https://mydomain.com/website2/, etc)

#### Expected result:
- every URL is generated without *index.php* and its URLs open correctly.

#### Actual result:
- every URL is generated without *index.php*, but only base website URLs work correct, other returns 404.

**Comment by NadiyaS** [comment]
Internal ticket is https://jira.corp.magento.com/browse/MCLOUD-2549
