### ISSUE TITLE
[ECE-Tools] Add Command to Display Values from Encoded Environment Variables

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#473]
Internal ID: `MAGECLOUD-3451`

### Background:
- We have a list of encoded variables on Cloud:
-- MAGENTO_CLOUD_RELATIONSHIPS
-- MAGENTO_CLOUD_ROUTES
-- MAGENTO_CLOUD_VARIABLES
- For better user experience, we need to add a command to ECE-Tools to show the values of those variables in a decoded format

### To Do:
- Add new command to display values of environment variables in an easier way than using decode commands.

**Comment by vkerkhoff** [comment]
@YPyltiai Is this available to create or is there already someone working on this? Any thoughts on how to display the information (like a formatted table or is a JSON output good enough), option to select which variable to display (or command per variable) and an option to show specific data within the variables?

**Comment by andriyShevtsov** [comment]
As far as I know nobody working on it yet. You can take this task if you want.

**Comment by YPyltiai** [comment]
@vkerkhoff JSON should be fine to start with as for me but we can look at options. For the command itself - I assume that having one command is better with possibility to provide argument which will define, which variables to decode.

@shiftedreality , since it was your proposal, do you have any comments on the above or you see it the same way?

CC: @oshmyheliuk , you may also have some inputs.

**Comment by shiftedreality** [comment]
I would try with Symfony's Table component. If it does not work - try with pretty json or pretty yaml

**Comment by oshmyheliuk** [comment]
I think Symfony Table won't work for displaying cloud configuration. It's better to use yaml or json.
We have thoughts to create one command with arguments, for example: 
```
ece-tools cloud:config  // show all (relationships, variables, routes)
ece-tools cloud:config relationships
ece-tools cloud:config variables
ece-tools cloud:config routes
``` 
Name `cloud:config` can be different but it should somehow emphasize which type of configuration it will return.

**Comment by vkerkhoff** [comment]
Ok, thanks! Will try to setup an initial implementation in the next few days and create a PR when ready.

**Comment by vkerkhoff** [comment]
I created a PR for this, it displays it in a table format which is easily readable. I didn't add any tests yet, let me know if this is what you were looking for so I see if I can also add some tests to it.
