### ISSUE TITLE
[ECE-Tools] Add Split DB Support

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#493]
Internal ID: `MAGECLOUD-3287`

**As** a Magento Cloud user, **I want** to be able supporting split DB, **so** I can offload part of DB-related operations to different instances to balance the load better and improve performance.

**To Do:**
* Add possibility to spin up additional separate DB instances and have ECE-Tools auto-configure routing and related settings:
** On separate hosts (separate tier)
** On same hosts as current DB (DB tier)
* New DB set can be configured and tuned independently from main DB
* Add possibility to migrate data from monolith DB to split DBs

**Comment by phoenix-bjoern** [comment]
IMHO this is a must-have feature. Otherwise you can't configure scalable checkout. This is definitely a missing feature for Magento Cloud.

**Comment by YPyltiai** [comment]
@phoenix-bjoern - it's in development now: #641
