### ISSUE TITLE
[ECE-Tools] WARM UP : error when no "default" store code

### ISSUE THREAD

**Issue by benjamin-volle** [magento/ece-tools#557]
### Preconditions
1. Magento 2.3.0
2. ece-tools 2002.0.20

### Steps to reproduce

1. Have a site without a store with code "default"
2. Set-up the WARM_UP_PAGES in the post-deploy node

### Expected result
1. Pages are warmed up

### Actual result

1. Error : Can't fetch base url. The command "php bin/magento config:show:store-url default" failed.

I guess there are many websites where the store with the "default" code have been removed. Why not taking "admin", which will (probably) never be deleted ?

**Comment by andriyShevtsov** [comment]
Hello. May you please explain which configuration of websites/store/ store views do you use. I created website with code `default` and without store and in my case it works correct.
By default after installation magento have 1 website with code `base` with related store and store view.

**Comment by andriyShevtsov** [comment]
May you please provide more details about  configuration of sites, stores  and store views. I created site with code `default` without store and it works correct. Maybe I missed something? 
<img width="1529" alt="Screen Shot 2019-07-08 at 3 10 51 PM" src="https://user-images.githubusercontent.com/25657845/60809163-ac541700-a192-11e9-8293-00d1980c05da.png">

**Comment by benjamin-volle** [comment]
Hi @andriyShevtsov 

This is precisely the problem : we don't have a "Store View" with the code "default".

**Comment by YPyltiai** [comment]
Will be resolved in #560
