### ISSUE TITLE
Download of media files shall skip cache directory

### ISSUE THREAD

**Issue by krisdante** [magento/ece-tools#595]
This is not a bug but rather an improvement request. 
Cache directories as it name depicts are media files that are generated - so they can be also re-generated. 
Size and number of this files is significant and there shall be at least a flag to exclude them from downloading when you just want to download media folder 

### Preconditions

1. Have Magento up and running with products with pictures

### Steps to reproduce

1. Execute `magento-cloud mount:download`
2. Choose pub/media
3. Files will be downloaded including `catalog/product/cache/`

### Expected result

1. It would be nice if there is additional option to omit files that are generated by Magento (and can be re-generated) 

### Actual result

1. Files will be downloaded including `catalog/product/cache/` and it takes a lot of time

**Comment by YPyltiai** [comment]
Hi @krisdante,

Thank you for submitting the request. We'll review it and will get back to you.

Thanks,
Yevhenii

**Comment by YPyltiai** [comment]
@andriyShevtsov , @mveeramneni , may you please validate the use case and see if this goes to ECE-Tools or rather https://github.com/magento/magento-cloud-cli ?

**Comment by krisdante** [comment]
You are tight. This is magento-cloud-cli. And I also realised that there is already --exclude filter and it's a matter to pass this parameter with proper value.
