### ISSUE TITLE
[Cloud CLI] magento-cloud build instruction removed from magento-cloud get command output

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/ece-tools#602]
As a manager of developers I want developers introduced to a Magento Cloud project to contribute code to that project as soon as possible.

After running a `magento-cloud get <project_id>` command, an instruction to run the `magento-cloud build` command is displayed. In the majority of use cases for `magento-cloud get`, `magento-cloud build` is not a legitimate next step. This instruction is incorrectly positioned. It is not a next step in getting a local environment running, authoring, or contributing code. 

After watching many first-time Cloud developers get started with their first task on a Cloud project, I find that the `magento-cloud build` command causes the following barriers to quickly contributing code to the project.

- The command causes changes that make it difficult to for the average developer to get the project running in a local environment.
- The command causes changes that dirty the repository which may result in incorrect code entering the project's repository.

I find that these problems occur with about 50% of developers.

### Steps to reproduce
Run `magento-cloud get` and observe the output.

### Expected result
`magento-cloud build` should not appear in output.

### Actual result
![2019-09-17_13-15-53](https://user-images.githubusercontent.com/23382713/65068422-3fa58780-d94e-11e9-9225-638f1c0ae67b.png)

**Comment by YPyltiai** [comment]
@joeshelton-wagento , if I got you right, do you request to have recommendations in the output fixed?

**Comment by joeshelton-wagento** [comment]
Removed, actually. Remove:

> You can build the project with: 
>     cd magento-u-sandbox-1
>     magento-cloud build

**Comment by YPyltiai** [comment]
Moved to Magento-cloud CLI repo. We will update you on status in this ticket @joeshelton-wagento . Thanks!
