### ISSUE TITLE
mutagen creates multiple stale sessions

### ISSUE THREAD

**Issue by aepod** [magento/ece-tools#603]
This ticket is also here.  https://github.com/magento/magento-cloud-docker/issues/55

### Preconditions
1. Have run mutagen.sh
2.  Subsequent runs create multiple mutagen sessions

### Steps to reproduce
1.  Set up docker with mutagen
2.  Run mutagen.sh
3.  Rerun mutagen.sh

### Expected result
1. Session would be recreated

### Actual result
1.  More than one session is created, old ones are stale

>[webuser@localhost project-m2]$ ./mutagen.sh
>Created session c75abb45-74ad-4cf0-ab3b-d3c51bf65a7a
>[webuser@localhost project-m2]$ ./mutagen.sh
>Created session bf2a3f2b-815b-43d3-9b9c-fafd806a6bfb
>[webuser@localhost project-m2]$ mutagen sync list
>--------------------------------------------------------------------------------
>Identifier: c75abb45-74ad-4cf0-ab3b-d3c51bf65a7a
>Labels: None
>Alpha:
>        URL: /home/webuser/docker/canon-m2
>        Connection state: Connected
>Beta:
>        URL: docker://e87016098b2bedfc25da6fd35ad9c5e7dd2eaacc104711765a2399866c6a7bb3/app
>                DOCKER_HOST=
>                DOCKER_TLS_VERIFY=
>                DOCKER_CERT_PATH=
>        Connection state: Connected
>Status: Scanning files
>--------------------------------------------------------------------------------
>Identifier: bf2a3f2b-815b-43d3-9b9c-fafd806a6bfb
>Labels: None
>Alpha:
>        URL: /home/webuser/docker/canon-m2
>        Connection state: Connected
>Beta:
>        URL: docker://e87016098b2bedfc25da6fd35ad9c5e7dd2eaacc104711765a2399866c6a7bb3/app
>                DOCKER_HOST=
>                DOCKER_TLS_VERIFY=
>                DOCKER_CERT_PATH=
>        Connection state: Connected
>Status: Scanning files
>--------------------------------------------------------------------------------

**Comment by aepod** [comment]
I have a good fix for this, will have a PR shortly.

**Comment by YPyltiai** [comment]
Hi @aepod ,

As discussed via Slack - let's have this one in https://github.com/magento/magento-cloud-docker, since we move all the functionality already there.

Thanks,
Yevhenii
