### ISSUE TITLE
Remove hard dependency on redis-cli

### ISSUE THREAD

**Issue by Flyingmana** [magento/ece-tools#669]
### Preconditions

1. Have an Environment / Docker container, which does not ship with the redis-cli

### Steps to reproduce

1.  Have an Environment / Docker container, which does not ship with the redis-cli
2. use ece-tools
3. failing because redis-cli is not available to execute flushdb

### Expected result

1. Instead of using the redis-cli, the same should be used, which is also used in Magento.
(Credis?) or the underlying php Redis Extension.

### Actual result

1.  failing because redis-cli is not available to execute flushdb
```
The command "redis-cli -h redis -p 6379 -n 0 flushdb" failed.
Exit Code: 127(Command not found)
```

### References
https://github.com/magento/ece-tools/issues/409
https://github.com/magento/ece-tools/pull/410

### Suggestions

Instead of just switching it out, would it be more acceptable if we make it configurable and just add it as optional alternative?

**Comment by shiftedreality** [comment]
We could potentially use credis extension

**Comment by YPyltiai** [comment]
Looks like @Flyingmana started working on it in #670
