### ISSUE TITLE
Add Versioning to Env Variable Schema

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#678]
**Background:**
- We've just added the schema for environment variables to be used with ECE-Tools here: https://github.com/magento/ece-tools/blob/develop/config/schema.yaml
- It contains all required information for 3-p tools and packages to be able working with variables reliably
- We miss the versioning though, so if something gets updated there - CICD tooling may never catch it.

**To Do:**
- Add version definition to https://github.com/magento/ece-tools/blob/develop/config/schema.yaml , so CICD tooling and automations may validate if they are using up to date variables.

**Comment by NadiyaS** [comment]
Internal ticket https://jira.corp.magento.com/browse/MCLOUD-5532 is done.
Issue is closed as resolved.
