### ISSUE TITLE
Add Concept of State-aware Error Codes to ECE-Tools

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#679]
**Background:**
- We currently use logger and actual process results separately, meaning that Critical / Warning will not always cause build / deployment to fail unless we explicitly do that.
- Error codes used are standard 0 / 1, letting us know that the process was successful or failed, without providing any context on state of the process and environment in which it exited with error. 
- Current error handling doesn't allow CICD systems properly handle errors unless there is heavy customization added to parse log output or post events to any hooks, etc.

**To Do:**
- Introduce concept of state-aware error codes, allowing us to understand in which exact state environment and deployment process ended up at the moment it failed.
- Provide extensibility mechanism, so 3-p CICD systems can read error codes before ece-tools exits with error.
- Main use cases:
   - State-specific (and/or custom) error handling
   - Automated recovery and rollbacks
   - Custom deployment logic extension based on error codes (example: notify 3-p systems of failed deploy)

**Comment by arhiopterecs** [comment]
### [Proposal] Concept of State-aware Error Codes to ECE-Tools

All defined errors and warnings from `ECE-tools` will be split into certain groups like: FS error, service configuration errors, SCD errors, etc.

Each error's group will be assigned to a unique error code's range to quickly identify the source of the fault.

Such error codes will be in the range of `1` to `255`

Example of a list of errors and messages of `ECE-tool`:
![Screen Shot 2020-04-30 at 9 16 58 AM](https://user-images.githubusercontent.com/1901448/80721683-22c85980-8ac4-11ea-97de-6fdc58c5b7a8.png)
...
![Screen Shot 2020-04-30 at 9 17 16 AM](https://user-images.githubusercontent.com/1901448/80721866-5a370600-8ac4-11ea-81a9-a9289325fc8a.png)
...
![Screen Shot 2020-04-30 at 9 17 29 AM](https://user-images.githubusercontent.com/1901448/80721890-61f6aa80-8ac4-11ea-8670-966fcfbcea4e.png)

---
![Screen Shot 2020-04-30 at 9 18 01 AM](https://user-images.githubusercontent.com/1901448/80721957-75a21100-8ac4-11ea-9b08-9ade8f296fe6.png)
...
![Screen Shot 2020-04-30 at 9 18 17 AM](https://user-images.githubusercontent.com/1901448/80721969-7a66c500-8ac4-11ea-8bce-3fa61bac6049.png)
...
![Screen Shot 2020-04-30 at 9 18 25 AM](https://user-images.githubusercontent.com/1901448/80721986-805ca600-8ac4-11ea-9adf-4c99283fd270.png)
----
Previous records of errors in `var/log/cloud.log` will be complemented by error codes.
`ECE-tools` will write all appeared warnings and critical error which terminate the script to separate file - `var/log/cloud.error.log`

This file will be created during the deployment which will have all errors/warnings happened in all phases. This data is written in runtime and file may already contain warnings which were appeared even before the end of the deployment.

The file has data only from the latest deployment (no previous history). If the file is empty - it means that none errors found during the deployment.

The file contains data in next format:

`<DATETIME> [<ERROR_CODE>]: <ERROR_TITLE> <DESCRIPTION>`

There are 2 types of records which may be written in `var/log/cloud.error.log`:
- warning messages
- critical errors which terminate the script.

All messages with possible solutions will be described in `ece-tools/config/schema.error.yaml` file which will give a possibility to add functionality based on error code.

**Pros:**

- As warnings/errors are written to the `var/log/cloud.error.log` file right after they were found, it always has an actual list even if the deployment script was unexpected terminated.

- Existence the records in this file always informs that there were some problems when the absence of the records in this file says that there is no warning/error during the last deployment.

- Other 3-p systems may immediately be informed when any warning happened during the deployment before finishing the process.

- In comparison to `var/log/cloud.log`, file `var/log/cloud.error.log` will have increased error description and appropriate solution where it is possible.

Authors: @NadiyaS, @oshmyheliuk

**Comment by NadiyaS** [comment]
Error codes for critical errors were delivered in ece-tools v.2002.1.1.
The rest of codes for warning errors were implemented in https://github.com/magento/ece-tools/pull/744 and will be delivered later.
Our documentation about error codes - https://devdocs.magento.com/cloud/reference/error-codes.html

This issue may be closed as done
