### ISSUE TITLE
Fix ideal state validation

### ISSUE THREAD

**Issue by shiftedreality** [magento/ece-tools#684]
ECE-Tools version 2002.1.0 throwing warning about the wrong format of `pos-deploy`, if the scenario is used.

```
[2020-02-12 14:28:54] WARNING: Fix configuration with given suggestions:
    - The configured state is not ideal
     Your application does not have the "post_deploy" hook enabled.
      In order to minimize downtime, add the following to ".magento.app.yaml":
      hooks:
        post_deploy: |
          php ./vendor/bin/ece-tools post-deploy
```

### Preconditions

1. The scenario used for post-deploy `./vendor/bin/ece-tools run scenario/post-deploy.xml`
2. Cloud project deployed

### Expected result

1. No warnings

### Actual result

1. Warnings in the log

**Comment by andriyShevtsov** [comment]
Internal issue MAGECLOUD-5295
