### ISSUE TITLE
Add ability to disable cron per environment

### ISSUE THREAD

**Issue by diazwatson** [magento/ece-tools#688]
Some times it is necessary to deactivate cron. This seems to be a common practice specially when trying to improve performance in shared environments like Integration environments.

Currently it is possible to do so by modifying the `.magento.app.yaml` file.

The problem with this approach is that disabling the cron using the `.magento.app.yaml` file wil deactivate cron in all environments.

**Comment by YPyltiai** [comment]
@diazwatson , doesn't https://devdocs.magento.com/cloud/configure/setup-cron-jobs.html#disable-cron-jobs work for your use case or you were not aware that this exists? If it doesn't work for you, would be great to get more details on the exact use case. Thanks!

**Note:** it is in ECE-Tools 2002.1.0

**Comment by diazwatson** [comment]
But is going to be overwritten in the next deployment. Is there a way to permanently disable cron for a specific environment?

**Comment by YPyltiai** [comment]
@diazwatson makes sense. I ran this by team - there is no way to do that now, so you can stop them from running on schedule but still have possibility to run them manually on demand. We'll need to look deeper into it. Thanks for bringing this up!

**Comment by shiftedreality** [comment]
Hello @diazwatson 

We've found a more elegant way to accomplish this:

Edit your `.magento.app.yaml` config with something like:

```
crons:
    cronrun:
        spec: "* * * * *"
        cmd: |
            if [ "$MAGENTO_CLOUD_BRANCH" = master ]; then
                php bin/magento cron:run
            fi
```

Make sure to adjust `"$MAGENTO_CLOUD_BRANCH" = master` to include `production` and `staging` branches.

**Comment by diazwatson** [comment]
Thanks for taking the time to investigate this @shiftedreality 
Does this mean that cron will not run in all environments but only in production and staging because they both inherit from master branch.

Also all environments inheriting from Integration will have cron disable.

Is this correct?

**Comment by shiftedreality** [comment]
Yes, you’ll only have to specify correct branch names

**Comment by diazwatson** [comment]
Oh, I have to specify each branch then
Is this correct?
```
crons:
    cronrun:
        spec: "* * * * *"
        cmd: |
            if [ "$MAGENTO_CLOUD_BRANCH" = master ]; then
                php bin/magento cron:run
            fi
            if [ "$MAGENTO_CLOUD_BRANCH" = production ]; then
                php bin/magento cron:run
            fi
            if [ "$MAGENTO_CLOUD_BRANCH" = staging ]; then
                php bin/magento cron:run
            fi
            if [ "$MAGENTO_CLOUD_BRANCH" = staging ]; then
                php bin/magento cron:run
            fi
```
@shiftedreality

**Comment by shiftedreality** [comment]
You can combine it into the one-line statement with regexp as well, something like this:

```
BRANCH_REGEX="^(master|staging|production)"

if [[ $MAGENTO_CLOUD_BRANCH =~ $BRANCH_REGEX ]]; then
    php bin/magento cron:run
fi
```

**Comment by YPyltiai** [comment]
@diazwatson , did it resolve your use case? Wanted to see if we can close this ticket.

**Comment by diazwatson** [comment]
It seems to be solved, thank you guys

**Comment by opepin** [comment]
@shiftedreality - I think you are missing a closing bracket 
```  BRANCH_REGEX="^(master|staging|production)"
 
 if [[ $MAGENTO_CLOUD_BRANCH =~ $BRANCH_REGEX ]]; then
     php bin/magento cron:run
 fi
```

**Comment by shiftedreality** [comment]
@opepin you're right, fixed

**Comment by shiftedreality** [comment]
More advanced example in case you want cron jobs run every 5 minutes on integration environments:

```
    cronrun:
        spec: "* * * * *"
        cmd: |
            BRANCH_REGEX="^(master|staging|production)"
            if [[ $MAGENTO_CLOUD_BRANCH =~ $BRANCH_REGEX ]]; then
                php bin/magento cron:run
            fi
    cronrun-integration:
        spec: "*/5 * * * *"
        cmd: |
            BRANCH_REGEX="^(master|staging|production)"
            if [[ ! $MAGENTO_CLOUD_BRANCH =~ $BRANCH_REGEX ]]; then
                php bin/magento cron:run
            fi
```
