### ISSUE TITLE
Set install date

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/ece-tools#696]
Magento saves hashes of the env.php and config.php in it's database to detect changes. When you deploy two fresh instances in parallel (without sharing app/etc/env.php) their install date in env.php will be different. This could lead to errors which only can be resolved by manual execution of `bin/magento app:config:import`.

The only difference we found in the env.php is the install date. If it would be possible to provide the install date similar to the CRYPT_KEY in the MAGENTO_CLOUD_VARIABLES environment variable the env.php of all freshly deployed instances would be identical. If the install date is not provided the date will be set by https://github.com/magento/ece-tools/blob/develop/src/Config/State.php#L90.

**Comment by YPyltiai** [comment]
Hi @phoenix-bjoern, may you please explain the impact of the date is not the same on two environments? Is the logic working any different there or it cannot see that this env.php is actually belonging to this environment?

**Comment by phoenix-bjoern** [comment]
As a pre-condition: app/etc is not on a shared folder (NFS). The reason for this is that app/etc/config.php sometimes doesn't get updated properly so we prefer to have a "shared nothing" installation.

Imagine you have an auto-scaling scenario and new pods/VMs - connected to the same database - are coming up on demand. If the install date is always different the config hash in the flag table gets updated which causes errors on the existing pods/VMs. Therefore it is necessary, that the env.php gets consistently generated whenever a new pod/VM (of the same build) gets deployed.

IMHO it is necessary - similar to the CRYPT_KEY - to have an INSTALL_DATE in the MAGENTO_CLOUD_VARIABLES environment variable. This will allow each new instance to generate an identical env.php and shouldn't cause any problem with the config hash in the database.

**Comment by NadiyaS** [comment]
Hi @phoenix-bjoern,
you mention that because of difference in installation date you have to run `bin/magento app:config:import`. But that hash which Magento stores in DB does not read this data at all. 
That hash stores data from `system` section (as merge from env.php and config.php). So check the difference there.

**Comment by phoenix-bjoern** [comment]
@NadiyaS you are right, it seems my observation was not accurate.
I'm closing this ticket and will open a new one if I'm able to find the root cause of the error we found in our deployment.
