### ISSUE TITLE
Add information about number of concurrency for warm-up into cloud.log

### ISSUE THREAD

**Issue by andriyShevtsov** [magento/ece-tools#701]
Recently was added ability to specify number of concurrent requests   for warm-up. (see PR https://github.com/magento/ece-tools/pull/700). 
It make sense to add information about number of concurrency into cloud.log otherwise it's not obvious to understand how much  concurrent requests were set. 

 It can be something like:

`Starting page warming up (concurrency: 3)`

**Comment by andriyShevtsov** [comment]
Internal ticket MAGECLOUD-5636

**Comment by NadiyaS** [comment]
Internal ticket https://jira.corp.magento.com/browse/MCLOUD-5563 is done.
Issue is closed as resolved
