### ISSUE TITLE
[Investigation] Indexers stuck after redeploy

### ISSUE THREAD

**Issue by BaDos** [magento/ece-tools#729]
### Preconditions
Looks like after killing processes before deploy phase some indexers can be stuck.

There is more information from community slack: https://magentocommeng.slack.com/archives/C8CBB6K9V/p1589463049184700

### Steps to reproduce

1. Try to redeploy when some indexer works

### Expected result

1. Indexers can be run

### Actual result

1. Some indexers can be stuck

Internal ticket: MCLOUD-5992

**Comment by YPyltiai** [comment]
@BaDos , did you have a chance to look into it?

**Comment by phoenix-bjoern** [comment]
Could you please consider adding support for the new use_application_lock setting (see https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html#using-application-lock-mode-for-reindex-processes)? This would help to mitigate this problem.

**Comment by phoenix-bjoern** [comment]
@andriyShevtsov Why has this issue been closed? Neither is the original problem solved nor has the new option use_application_lock been implemented. By closing this issue you just ignore the fact that indexation stays in a bad state after deployment and ece-tools doesn’t try to help with it.
