### ISSUE TITLE
[Feature request] Leave site in maintenance mode post-deploy

### ISSUE THREAD

**Issue by ngreimel-lt** [magento/ece-tools#733]
After a Cloud deployment, additional scripts or configuration may need to take place. Sometimes the site may be non-functional until these processes are complete. It would be nice to have the option to leave the site in maintenance mode post-deploy, and let the deployer run `bin/magento maintenance:disable` to bring the site back online when appropriate.

**Comment by NadiyaS** [comment]
Hi @ngreimel-lt ,
I would even recommend to remove step on deploy phase where this mode is disabled https://github.com/magento/ece-tools/blob/develop/scenario/deploy.xml#L123 and disable it in the post-deploy script where you need it, but before `warm-up` step https://github.com/magento/ece-tools/blob/develop/scenario/post-deploy.xml#L17
You can find all information how to customize ece-tools scenarios in our documentation - https://devdocs.magento.com/cloud/deploy/scenario-based-deployment.html#remove-default-steps.

**Comment by NadiyaS** [comment]
Hi @ngreimel-lt,

As your request does not require changes in ece-tools and only adding custom scenarios, I close this issue.
Feel free to open new issue if you have new proposals of meet any issue.
For any questions you also may use our [Magento Commerce Cloud Channels](https://opensource.magento.com/slack-channels)
