### ISSUE TITLE
Adjust SCD Process & Variables to Work with New SCD Improvements

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#785]
Once https://github.com/magento/magento2/pull/30090 is merged, we need to adjust ECE-Tools default SCD process and variables to account for changes for new Magento versions:
- We should be able to configure the updated SCD flow leaving current one as default for now;
- We should consider back-porting changes to earlier version if possible;
- Ideally would be to add automation to test SCD speed so we can track changes / improvements / degradation over time.

**Comment by ihor-sviziev** [comment]
> Ideally would be to add automation to test SCD speed so we can track changes / improvements / degradation over time.

👍

**Comment by ihor-sviziev** [comment]
Pull request to magento2 repo was already merged, so we can already work on implementing support in ece tools

**Comment by NadiyaS** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7284) is successfully created for this issue.

**Comment by ihor-sviziev** [comment]
@YPyltiai was this fixed?

**Comment by NadiyaS** [comment]
hi @ihor-sviziev 
Ece-tools supports that feature (for now in developer branch only). It will be delivered in next release. See https://github.com/magento/ece-tools/commit/5323bf5c38636f15a0a5766b20e2f0bbec6b91af
