### ISSUE TITLE
Add ES to compatibility service version validator

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/ece-tools#786]
ES is not included to the list of services for version compatibility with Magento <https://github.com/magento-commerce/ece-tools/blob/develop/src/Config/Validator/Deploy/ServiceVersion.php#L62>

Need to check that whether this validation is implemented in another step, otherwise add ES to service version validator

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MCLOUD-7193

**Comment by andriyShevtsov** [comment]
QA approved
