### ISSUE TITLE
Ece-tools Upgrade to 2002.1.3 breaks the environment with Search engine "elasticsuite"

### ISSUE THREAD

**Issue by samc2810** [magento/ece-tools#787]
### Preconditions

1. Magento cloud 2.4.1
1. ece-tools 2002.1.3
1. elasticsuite latest

### Steps to reproduce
1. Just deploy an upgraded composer.lock

### Expected result

1. Deployment is normal

### Actual result

1. ![image](https://user-images.githubusercontent.com/1092318/98680060-2c7b2580-2361-11eb-886d-e76e3130bec0.png) 
Ece-tools fails the deployment with message that elasticseach requires to be set as search engine

Downgrading the ece-tools to 2002.1.2 works just fine

Cheers

**Comment by NadiyaS** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7283) is successfully created for this issue.

**Comment by NadiyaS** [comment]
Hi @samc2810,
thank you for reporting this issue. Created internal issue is MCLOUD-7283

**Comment by NadiyaS** [comment]
Hi @samc2810 ,
this issue was fixed, please upgrade ece-tools to 2002.1.4 version.
I close this issue as solved.
