### ISSUE TITLE
Unlock cron jobs in-appropriate comments

### ISSUE THREAD

**Issue by manaftryzens** [magento/ece-tools#791]
**Unlock cron job says it update the running jobs as missed**
https://github.com/magento/ece-tools/blob/develop/src/Step/Deploy/UnlockCronJobs.php says it updates the cron jobs from running status to "missed" status. But it actually updates them as "error"

**Modify the comments**
Modify the comments at https://github.com/magento/ece-tools/blob/develop/src/Step/Deploy/UnlockCronJobs.php , as it should say ' Moves all cron jobs from status running to status "error" '.

**Comment by andriyShevtsov** [comment]
Should be fixed now
