### ISSUE TITLE
Composer 2 is not supported

### ISSUE THREAD

**Issue by osrecio** [magento/ece-tools#797]
Have you plan to support Composer 2?

Refering to this requirement: https://github.com/magento/ece-tools/blob/2002.1/composer.json#L19

**Comment by oshmyheliuk** [comment]
Hi @osrecio ,
Thank you for creating an issue.
We already have an internal ticket to add Composer 2 support it will be done before the next release.

**Comment by hardyjohnson** [comment]
Can this be closed with the support being released? https://devdocs.magento.com/cloud/release-notes/ece-release-notes.html#v200217

**Comment by oshmyheliuk** [comment]
@hardyjohnson thanks, closed
