### ISSUE TITLE
ECE tools ComposerFile check not compatible with M2.4.3

### ISSUE THREAD

**Issue by leonhelmus** [magento/ece-tools#798]
When deploying to a feature environment with parent integration i get the following error:
`CRITICAL: [9] Required configuration is missed in autoload section of composer.json file.
    Add ("Laminas\Mvc\Controller\: "setup/src/Zend/Mvc/Controller/") to autoload -> psr-4 section and re-run "composer update" command locally. Then commit new composer.json and composer.lock files.`, but when i look in the code base of magento 2.4.3: https://github.com/magento/magento2/blob/2.4.3/composer.json and compare it to 2.4.2. "Laminas\Mvc\Controller\: "setup/src/Zend/Mvc/Controller/" was removed on purpose in the upgrade.
### Preconditions

1. M2.4.3, PHP 7.4, MariaDB 10.4, Redis 5.0, composer 1
2. Deploy to any magento cloud environment using magento-cloud environment:push

### Steps to reproduce

1. Upgrade magento cloud to 2.4.3 ("magento/magento-cloud-metapackage": ">=2.4.3 <2.4.4")
2. Use composer root update plugin to update your composer.json with the latest changes using:
`composer require magento/product-enterprise-edition:2.4.3 --base-magento-edition 'Commerce' --base-magento-version 2.4.2-p1 --no-update`
3. Upgrade magento using composer update.
4. After everything has been succesfully upgraded deploy to a feature env that has integration as a parent.
5. Deployment gives the following error:
`Executing build hook...
    [2021-08-26 09:29:00] INFO: Starting scenario(s): scenario/build/generate.xml (magento/ece-tools version: 2002.1.7, magento/magento2-base version: 2.4.3)
    [2021-08-26 09:29:02] INFO: Verbosity level is not set
    [2021-08-26 09:29:02] NOTICE: Applying patches
    [2021-08-26 09:29:03] NOTICE: End of applying patches
    [2021-08-26 09:29:03] INFO: Set Magento application mode to 'production'
    [2021-08-26 09:29:03] NOTICE: Validating configuration
    [2021-08-26 09:29:03] NOTICE: Fix configuration with given suggestions:
    [2021-08-26 09:29:03] CRITICAL: [9] Required configuration is missed in autoload section of composer.json file.
    Add ("Laminas\Mvc\Controller\: "setup/src/Zend/Mvc/Controller/") to autoload -> psr-4 section and re-run "composer update" command locally. Then commit new composer.json and composer.lock files.
    [2021-08-26 09:29:03] ERROR: [9] Required configuration is missed in autoload section of composer.json file.
    W: 
    W: In Processor.php line 129:
    W:                                                                                
    W:   Required configuration is missed in autoload section of composer.json file.  
    W:                                                                                
    W: 
    W: In ValidateConfiguration.php line 69:
    W:                                                                                
    W:   Required configuration is missed in autoload section of composer.json file.  
    W:                                                                                
    W: 
    W: build:generate
    W: 
  
  E: Error building project: Step failed with status code 9.

E: Error: Unable to build application, aborting.`

### Expected result

deploys correctly without errors.

### Actual result

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/18070887/130960958-2ba6c20d-4434-4fd7-9c18-432c7837a67d.png)

**Comment by igorwulff** [comment]
Can this be given high priority? Since a vanilla Magento 2.4.3 installation will now break for Magento Cloud deployments.

**Comment by leonhelmus** [comment]
I created a PR to resolve this issue: https://github.com/magento/ece-tools/pull/799

**Comment by leonhelmus** [comment]
This has been resolved.
