### ISSUE TITLE
php 8.1 support

### ISSUE THREAD

**Issue by glo45343** [magento/ece-tools#803]
vendor/bin/ece-tools build

Fatal error: During inheritance of ArrayAccess: Uncaught RuntimeException: 
Deprecated Functionality: Return type of Illuminate\Config\Repository::offsetExists($key) 
should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool,
 or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress 
the notice in /var/workspace/vendor/illuminate/config/Repository.php on line 141 
in /var/workspace/vendor/magento/ece-tools/src/App/ErrorHandler.php:68
Stack trace:

**Comment by glo45343** [comment]
Problem 1
    - Root composer.json requires magento/ece-tools >=2002.1.8 -> satisfiable by magento/ece-tools[2002.1.8].
    - magento/ece-tools 2002.1.8 requires php ^7.1.3 -> your php version (8.1.2) does not satisfy that requirement.

**Comment by andriyShevtsov** [comment]
php 8.1 support added
