### ISSUE TITLE
Cache is flushed multiple times during deployment

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/ece-tools#805]
The deploy scenario clears caches in the "pre-deploy" and "deploy-complete" steps (see https://github.com/magento/ece-tools/blob/develop/scenario/deploy.xml). In MAGECLOUD-1203 (#80) an additional "clean-cache" step is added to the update step for no reason (see deploy.xml in commit https://github.com/magento/ece-tools/commit/c5fe5aff8c489a2e0887d5fe2b1813de5a1c35e6). 

While this unnecessarily cache flush adds a few seconds to each deployment it also changes the behavior of our customized deployment scenario which usually tries to avoid cache flushes by using a "per deployment" id_prefix for the Redis cache which "namespaces" the cache for each build/deployment.

**Comment by andriyShevtsov** [comment]
@BaDos  please leave comment and close

**Comment by BaDos** [comment]
Hi @phoenix-bjoern 
We need to keep this step because when users try to configure the DB connections, for example, to another service it causes failure without cache cleaning. The cache has old connection information.
